### ISSUE TITLE
Add inline markdown formatter

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5-autoformat#3] opened 2016-10-12 10:19 UTC
Example of expected behaviour (details to be discussed):
1. Type `foo`,
2. Type `**`,
3. `**` is removed and bold is applied (on collapsed selection),
4. Type `bar`. (bold text will be inserted automatically)?
5. Type `**`,
6. `**` is removed and bold is removed from selection,
7. Type `bom` (normal text will be inserted).

To be defined whether a styling characters ("*", "~") should be visible in the editable or not.

**Comment by Reinmar** [comment] 2016-10-12 10:34
> To be defined whether a styling characters ("*", "~") should be visible in the editable or not.

During the hackathon we made the characters visible: https://github.com/ckeditor/ckeditor5-hackathon/issues/4.

But I think that this is a different type of feature. It'd be more useful for editors in which you work on source code (markdown source) and see the formatting inline. What we want to achieve here, just like in #1, is to improve the UX by allowing to quickly format the text (without using mouse or special keystrokes).

Besides, in #1 we haven't made the characters visible, so we should be consequent here ;).

**Comment by Reinmar** [comment] 2016-10-12 10:36
BTW, I've got problem with one scenario. In MD bold is applied by `**foo**` and italic can be applied by `*foo*`. So when user types `*`, we don't know yet what styling option should be applied. Hence, the feature must work like this:

1. Type `*`. Nothing happens.
1. Type `**`. Nothing happens.
1. Type `x`. The `**` is removed and `x` is bolded.
1. Type `*`. Nothing happens.
1. Type `*`. Bold is removed from selection and `**` is removed.

**Comment by maxbarnas** [comment] 2016-10-12 11:03
What about deleting ("backspacing") text? There won't be sudden change of bolded text to **text**?

**Comment by Reinmar** [comment] 2016-10-12 12:37
I don't understand about what case you're asking. Could you elaboratE?

**Comment by maxbarnas** [comment] 2016-10-12 12:40
(I updated example in my question above).

I meant: does the application of bold style is reversible?

**Comment by Reinmar** [comment] 2016-10-12 12:49
I don't think so. Not in this way. It should be possible to undo the autoformatting action, though, just like in the block autoformatting case.

**Comment by maxbarnas** [comment] 2016-10-13 09:12
Hackathon solution was to start at the currently inserted element, then traverse up the tree of elements, remove all `*-md` attributes, then re-apply them to that tree. It was possible because MD characters (like `**`) were still there. This solution is useless if we want to remove those characters.

I considered another way where I check inserted characters and apply styling when approaching a set of MD characters, but this will fail if someone changes selection and start typing in a different place.

My solution would work If I were checking if recently typed characters were siblings. But I feel there are lots of edge cases to cover. 

For example: move cursor to a place with one `*` and type in another `*`. Should this trigger autoformatting?

(Disclaimer: I use the phrase _MD characters_ for simplification. I know this won't be an actual MD formatter).

**Comment by maxbarnas** [comment] 2016-10-13 15:01
I decided (at least for now) to go with triggering inline autoformat only when the actual pattern is typed character after the character. 

An example below will **not trigger** autoformat.

`foo*bar[]` -> `foo*[]bar` -> `foo**[]bar`

This will:

`foo*[]` -> `foo**[]`

**Comment by Reinmar** [comment] 2016-10-13 15:30
Do you mean that it will work only at the end of line? This may be confusing and simply less useful.

**Comment by maxbarnas** [comment] 2016-10-13 15:32
This will work when you type consecutive set of pattern characters. For example, if a pattern is `**` then you have to type both of them to make next characters you type bolded. This means it will work in the middle of the line, but it won't change existing text to bold, only text you are about to type.

**Comment by fredck** [comment] 2016-10-13 15:40
Hum... the problem is that you have to, as well, tell when do you want the style to stop. In `sample **bold** text` you don't want bold to start on "b" and be active forever. If I would have to type again `**` to disable the style, it may be counterintuitive.

I would propose replacing the whole thing only once the "closing pattern" is typed, like in the following typing worflow:

 * `sample `
 * `**` // Nothing happens
 * `bold`
 * `**` // `**bold**` is replaced with **bold**

**Comment by maxbarnas** [comment] 2016-10-13 15:48
@fredck This means that this functionality will be much more similar to Hackathon solution of Markdown. I have nothing against that, we just need to agree to one use case.

Mine was more like a replacement for <kbd>Ctrl+B</kbd> while typing, but @fredck's solution is less surprising for a user (and is not just a copy of a keyboard shortcut).

**Comment by fredck** [comment] 2016-10-13 15:51
Yes, much like that, with the exception that it removes the formatting markers from the text.

**Comment by Reinmar** [comment] 2016-10-13 16:00
> Hum... the problem is that you have to, as well, tell when do you want the style to stop. In sample **bold** text you don't want bold to start on "b" and be active forever. If I would have to type again ** to disable the style, it may be counterintuitive

Hm... I feel the other way. That if you won't see that `**` actually does something, then you may not be tempted to type the rest (`foo**`). But this isn't something critical so it could work as you proposed. I'm fine with that.

**Comment by maxbarnas** [comment] 2016-10-13 16:18
Before I agree to one or the other workflow, I must ask - what if there is already, somewhere down the document a  `**` pattern (or any other pattern that might come up in future)? A whole text between becomes bold. Yeah, we can use undo to revert that, but is it a really useful functionality?

In the Slack, those patterns work as an aid to styling otherwise plain text. They are applied when you send a message (or when you are editing it - but editing brings back those styling patterns, so you can change them).

In a regular editor, like CKE,  you can select text and apply a style. To make currently typed text bold you can use a keyboard shortcut.

Where in the editing workflow fits our inline autoformatting? **What actual problems does it solve?**

**Comment by Reinmar** [comment] 2016-10-13 16:38
> what if there is already, somewhere down the document a `**` pattern (or any other pattern that might come up in future)? A whole text between becomes bold. Yeah, we can use undo to revert that, but is it a really useful functionality?

Good question, but I think that this is an acceptable edge case.

> Where in the editing workflow fits our inline autoformatting? What actual problems does it solve?

The same as with autoformatting for blocks. We allow to apply a style without knowing keystrokes and taking your hands of the keyboard. Also, many people are used to Markdown styling so it should be natural for them.

**Comment by maxbarnas** [comment] 2016-10-13 16:48
> this is an acceptable edge case

If we also want to use `*` as an italic formatting pattern, I can imagine how many times someone will start to edit existing text and accidentally triggers this autoformatting for a whole block of text.

If we consider that as a problem, then my initial solution (and @Reinmar's) is less error prone than @fredck's.

Please, rethink that before we decide.

**Comment by fredck** [comment] 2016-10-18 09:45
I think it is sensible to limit the feature to the current block of text only. In any way, we should just proceed with the approach we already decided to go with: apply the style when "closing".

**Closed** 2016-10-31 16:46 UTC
Labels: status:confirmed, status:onreview, type:task
